### ISSUE TITLE
AttributeError: 'QWenTokenizer' object has no attribute 'IMAGE_ST'

### ISSUE THREAD

**Issue by kailinjiang** [VLKEB/VLKEB#8]
Traceback (most recent call last):
  File "/scratch2/mas/jiangkailin/jkl/MMKE/VLKEB_F/multimodal_edit_2.py", line 591, in 
<module>
    globals()[function_name]()
  File "/scratch2/mas/jiangkailin/jkl/MMKE/VLKEB_F/multimodal_edit_2.py", line 295, in 
train_SERAC_Blip2OPT
    trainer.run()
  File "/scratch2/mas/jiangkailin/jkl/MMKE/VLKEB_F/easyeditor/trainer/BaseTrainer.py", 
line 219, in run
    archive = torch.load(self.save_path, map_location="cpu")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jiangkailin/miniconda3/envs/vlkeb_1/lib/python3.11/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jiangkailin/miniconda3/envs/vlkeb_1/lib/python3.11/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jiangkailin/miniconda3/envs/vlkeb_1/lib/python3.11/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './results/models/SERAC_MULTI/blip2_240912_192846'

![6bd2dfe2b104b767b30db40557a751e](https://github.com/user-attachments/assets/17330ed7-aab2-40e3-82e1-0131118a3319)

**Comment by JZSAWYER** [comment]
Hi Kailin,
I have updated the necessary environment for running the Qwen model code. The new environment is at [vlkeb_qwenvl](https://github.com/VLKEB/VLKEB/blob/main/envs/vlkeb_qwenvl.yml). Thank you for your kind reminder!

**Comment by kailinjiang** [comment]
Thank you for your work!

**Comment by kailinjiang** [comment]
> Hi Kailin, I have updated the necessary environment for running the Qwen model code. The new environment is at [vlkeb_qwenvl](https://github.com/VLKEB/VLKEB/blob/main/envs/vlkeb_qwenvl.yml). Thank you for your kind reminder!

Could you please update the KE code of qwen-vl
Have urgent use, thank you!!

**Comment by JZSAWYER** [comment]
> > Hi Kailin, I have updated the necessary environment for running the Qwen model code. The new environment is at [vlkeb_qwenvl](https://github.com/VLKEB/VLKEB/blob/main/envs/vlkeb_qwenvl.yml). Thank you for your kind reminder!
> 
> Could you please update the KE code of qwen-vl Have urgent use, thank you!!

Hi, Kailin. We have updated the multi-hop code for both the qwen-vl and owl-2 models.
